---
name: DBIx-Custom-SQLite
version: 0.0102
author:
  - 'Yuki Kimoto <kimoto.yuki@gmail.com>'
abstract: DBIx::Custom SQLite implementation
license: perl
resources:
  license: ~
requires:
  DBD::SQLite: 1.25
  DBIx::Custom::Basic: 0.0101
build_requires:
  Test::More: 0
provides:
  DBIx::Custom::SQLite:
    file: lib/DBIx/Custom/SQLite.pm
    version: 0.0102
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
